### ISSUE TITLE
Couverture des tests

### ISSUE THREAD

**Issue by xenom34** [xenom34/lacompagnie#17]
# En bref

Résoudre certains récents problèmes concernant la couverture des tests du backend.

# Objectifs

    Stabilité du code
    Fiabilité du code

La résolution de cette issue se traduit par une livraison d'une branche, livrant des modifications apportés au code du serveur + index.test.js

**Comment by xenom34** [comment]
Extrait du dernier test :

```log
"C:\Program Files\nodejs\node.exe" --require "C:\Program Files\JetBrains\WebStorm 2022.2.2\plugins\javascript-impl\helpers\jest-intellij\lib\jest-intellij-stdin-fix.js" C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest\bin\jest.js --colors --reporters "C:\Program Files\JetBrains\WebStorm 2022.2.2\plugins\javascript-impl\helpers\jest-intellij\lib\jest-intellij-reporter.js" --verbose --runTestsByPath C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js
  console.log
    Serveur à l'écoute 4318

      at Server.log (index.js:455:36)

  console.log
    null

      at log (index.js:76:13)

  console.log
    Connected successfully to server

      at log (index.js:22:17)

  console.log
    null

      at log (index.js:76:13)

  console.log
    null

      at log (index.js:76:13)


Error: expect(received).toEqual(expected) // deep equality

Expected: 200
Received: 400
<Click to see difference>


    at Object.toEqual (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:135:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  console.log
    {}

      at log (index.js:31:13)

  console.log
    { _id: new ObjectId("63b979bc74023f6a7623f829") }

      at log (index.js:31:13)

  console.log
    undefined

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    undefined

      at log (index.js:229:17)

  console.log
    undefined

      at log (index.js:230:17)


Error: expect(received).toEqual(expected) // deep equality

- Expected  - 1
+ Received  + 5

  Array [
    Object {
      "errorType": "The first name is mandatory",
      "field": "fName",
-     "input": undefined,
+   },
+   Object {
+     "errorType": "This email address already exists",
+     "field": "email",
+     "input": "john.doe@example.fr",
    },
  ]
<Click to see difference>


    at Object.toEqual (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:171:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: expect(received).toEqual(expected) // deep equality

- Expected  - 1
+ Received  + 5

  Array [
    Object {
      "errorType": "the last name is mandatory",
      "field": "lName",
-     "input": undefined,
+   },
+   Object {
+     "errorType": "This email address already exists",
+     "field": "email",
+     "input": "john.doe@example.fr",
    },
  ]
<Click to see difference>


    at Object.toEqual (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:190:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: expect(received).toEqual(expected) // deep equality

Expected: 400
Received: 500
<Click to see difference>


    at Object.toEqual (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:226:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: expect(received).toEqual(expected) // deep equality

- Expected  - 1
+ Received  + 5

  Array [
    Object {
      "errorType": "The birth date is mandatory",
      "field": "birtDate",
-     "input": undefined,
+   },
+   Object {
+     "errorType": "This email address already exists",
+     "field": "email",
+     "input": "john.doe@example.fr",
    },
  ]
<Click to see difference>


    at Object.toEqual (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:247:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: expected 500 "Internal Server Error", got 401 "Unauthorized"

    at Object.expect (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:310:14)
    at Promise.then.completed (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\utils.js:290:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\utils.js:223:10)
    at _callCircusTest (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\run.js:248:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _runTest (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\run.js:184:3)
    at _runTestsForDescribeBlock (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\run.js:86:9)
    at _runTestsForDescribeBlock (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\run.js:81:9)
    at run (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\run.js:26:3)
    at runAndTransformResultsToJestFormat (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:120:21)
    at jestAdapter (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapter.js:79:19)
    at runTestInternal (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-runner\build\runTest.js:367:16)
    at runTest (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\jest-runner\build\runTest.js:444:34)
----
    at Test._assertStatus (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\supertest\lib\test.js:252:14)
    at C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\supertest\lib\test.js:308:13
    at Test._assertFunction (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\supertest\lib\test.js:285:13)
    at Test.assert (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\supertest\lib\test.js:164:23)
    at Server.localAssert (C:\Users\micha\WebstormProjects\lacompagnie\server\node_modules\supertest\lib\test.js:120:14)
    at Object.onceWrapper (node:events:639:28)
    at Server.emit (node:events:520:28)
    at emitCloseNT (node:net:1677:8)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
  console.log
    2023-07-31

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    undefined

      at log (index.js:229:17)

  console.log
    undefined

      at log (index.js:230:17)

  console.log
    2023-07-31

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    undefined

      at log (index.js:229:17)

  console.log
    undefined

      at log (index.js:230:17)

  console.log
    2023-07-31

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    undefined

      at log (index.js:229:17)

  console.log
    undefined

      at log (index.js:230:17)

  console.log
    2023-07-3

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    3830

      at log (index.js:229:17)

  console.log
    3682

      at log (index.js:230:17)

  console.log
    2023-07-31

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    3830

      at log (index.js:229:17)

  console.log
    3682

      at log (index.js:230:17)

  console.log
    2023-07-31

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    3830

      at log (index.js:229:17)

  console.log
    3682

      at log (index.js:230:17)


Error: expect(received).toBe(expected) // Object.is equality

Expected: 400
Received: 500
<Click to see difference>


    at Object.toBe (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:357:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  console.log
    2023-07-31

      at log (index.js:225:17)

  console.log
    undefined

      at log (index.js:226:17)

  console.log
    3830

      at log (index.js:229:17)

  console.log
    3682

      at log (index.js:230:17)

  console.log
    { _id: { '$eq': new ObjectId("63d98b13731d40fce666cb33") } }

      at log (index.js:31:13)

  console.log
    {
      date_departure: { '$eq': 2023-07-31T00:00:00.000Z },
      airport_departure: 3682,
      airport_arrival: 3830
    }

      at log (index.js:31:13)

  console.log
    { flight: new ObjectId("63989842f0298246cc397fed"), class: 'f' }

      at log (index.js:31:13)
          at Array.filter (<anonymous>)

  console.log
    { flight: new ObjectId("6398a55db40bf28c593d5bb7"), class: 'f' }

      at log (index.js:31:13)
          at Array.filter (<anonymous>)

  console.log
    { flight: new ObjectId("6398a817b40bf28c593d5bff"), class: 'f' }

      at log (index.js:31:13)
          at Array.filter (<anonymous>)


Error: expect(received).toMatchObject(expected)

- Expected  - 3
+ Received  + 0

@@ -6,11 +6,10 @@
        "airport_arrival": 3830,
        "airport_departure": 3682,
        "date_arrival": "2023-08-01T00:00:00.000Z",
        "date_departure": "2023-07-31T00:00:00.000Z",
        "duration": 190,
-       "price_first": 1500,
        "time_arrival": 670,
        "time_departure": 480,
      },
      Object {
        "_id": "6398a55db40bf28c593d5bb7",
@@ -18,11 +17,10 @@
        "airport_arrival": 3830,
        "airport_departure": 3682,
        "date_arrival": "2023-08-01T00:00:00.000Z",
        "date_departure": "2023-07-31T00:00:00.000Z",
        "duration": 190,
-       "price_first": 850,
        "time_arrival": 670,
        "time_departure": 480,
      },
      Object {
        "_id": "6398a817b40bf28c593d5bff",
@@ -30,11 +28,10 @@
        "airport_arrival": 3830,
        "airport_departure": 3682,
        "date_arrival": "2023-08-01T00:00:00.000Z",
        "date_departure": "2023-07-31T00:00:00.000Z",
        "duration": 190,
-       "price_first": 1000,
        "time_arrival": 670,
        "time_departure": 480,
      },
    ],
  }

    at Object.toMatchObject (C:\Users\micha\WebstormProjects\lacompagnie\server\index.test.js:403:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
  console.log
    { _id: 9586237 }

      at log (index.js:31:13)

  console.log
    { _id: 9586237 }

      at log (index.js:31:13)

  console.log
    { _id: 9586237 }

      at log (index.js:31:13)

  console.log
    { _id: new ObjectId("63d98b13731d40fce666cb33") }

      at log (index.js:31:13)

  console.log
    { _id: new ObjectId("63d98b13731d40fce666cb33") }

      at log (index.js:31:13)

  console.log
    { _id: new ObjectId("63d98b13731d40fce666cb33") }

      at log (index.js:31:13)

  console.log
    { _id: new ObjectId("63d98b13731d40fce666cb33") }

      at log (index.js:31:13)


```
